# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10)),
                ('user', models.OneToOneField(
                            on_delete=django.db.models.deletion.CASCADE,
                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(
                                        default=django.utils.timezone.now)),
                ('score', models.IntegerField()),
                ('movie', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to='movies.Movie')),
                ('rater', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to='movies.Rater')),
            ],
        ),
    ]
